stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: maven
    artifact_dir: 'target'
    script: |-
      #!/bin/bash

      # Package the compiled code in its distributed format (.jar) and store
      # it in the 'target' output directory
      mvn -B package

      # Copy the wksdeploy manifest.yml file to the 'target' directory as well
      # to have it available in the 'Deploy stage'
      cp manifest.yml $ARCHIVE_DIR
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REGION
    value: ${CF_REGION_ID}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    artifact_dir: ''
    deploy_type: cf
    target:
      region_id: ${CF_REGION_ID}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
      api_key: ${API_KEY}
    script: |-
      #!/bin/bash
      # Obtaining last portion of ibm:yp:<region> to get the <region>
      REGION=$(echo $REGION |cut -f 3 -d :)
      
      ibmcloud login -a cloud.ibm.com --apikey ${PIPELINE_BLUEMIX_API_KEY} -r ${REGION}
      ibmcloud target -o ${CF_ORG} -s ${CF_SPACE}

      ################################################################
      # Test cloud functions part of IBM Cloud CLI before deploying
      ################################################################

      echo 'List all entities in the current targeted namespace...'
      ibmcloud fn api list

      ################################################################
      # Deploy
      ################################################################

      echo "Running wskdeploy..."
      ibmcloud fn deploy -m "manifest.yml"
